Add A Simulator
All-Your-Locks-Are-Belong-To-Us/libmicrofido2 pull request #17
Opened 2022-07-09 12:02 UTC by felix-gohla

Not pretty but works :). 
Assumes knowledge about when which data is to be fetched when (some kind of white-box approach).

Closes #16

2022-07-09 13:16 UTC, sirkrypt0 requested changes

2022-07-09 13:16 UTC, sirkrypt0 commented on include/utils.h
> +#elif defined __APPLE__
`defined` with or without brackets?

2022-07-13 08:44 UTC, felix-gohla commented on include/utils.h
> +#elif defined __APPLE__
With brackets for consistency.

2022-07-20 07:58 UTC, sirkrypt0 approved these changes

2022-07-20 08:02 UTC, merged