Enable Hardware Crypto For nRF52840 NFC example
All-Your-Locks-Are-Belong-To-Us/libmicrofido2 pull request #27
Opened 2022-08-03 16:30 UTC by felix-gohla

2022-08-08 14:36 UTC, sirkrypt0 approved these changes

2022-08-09 15:31 UTC, felix-gohla commented
@sirkrypt0 Rebased and fixed some things.

2022-08-10 08:14 UTC, sirkrypt0 commented on examples/nfc_sim/nfc_simulator.c
> +    printf("open\n");
Those `printf` should all be `log`, no?

2022-08-10 11:46 UTC, sirkrypt0 approved these changes

2022-08-10 12:28 UTC, felix-gohla commented
@sirkrypt0 Again rebased after merging #26.

2022-08-11 09:34 UTC, sirkrypt0 requested changes

2022-08-11 09:34 UTC, sirkrypt0 commented on examples/nrf52/src/main.c
> +        printk("Could not setup simulator device.\n");
Should we return here?

```suggestion
        printk("Could not setup simulator device.\n");
        return -1;
```

2022-08-11 19:11 UTC, sirkrypt0 approved these changes

2022-08-11 20:12 UTC, merged